### PR TITLE
refactor CMakeLists.txt files

### PR DESCRIPTION
**Pull request by ycollet**
Put package detection in the main CMakeLists.txt file.
Put compiler flags in the main CMakeLists.txt file.

### CODE REVIEW

**Comment by ssj71** [comment]
I can't look at this for a couple days but I appreciate the pull request! I'll go over this as soon as I get a chance!

**Comment by ssj71** [comment]
ok, I've looked at this. This breaks the ability to build any single plugin by running cmake in its individual folder. What is the reason for these changes you propose to the cmake files?

**Comment by ycollet** [comment]
Most of the time, when you compile plugins, you compile all the set of 
plugins depending on the libraries discovered on your system.
For example, for the plugin depending on zita resampler, if zita 
resample is not found on your system, then all the plugins will be built 
excepted the one depending on zita resampler.
That's why I adjusted the CMakeLists.txt files like this.
On advantage: all the discovery machinery is centralized in one 
CMakeLists.txt file. The other advantage: if you want to change the 
compiler flags, then this can be done in the main CMakeLists.txt file.

Best regards,

YC

**Comment by ssj71** [comment]
I really appreciate the pull request, but for now I use single plugin builds very frequently during development, so I'm going to skip this. Thanks anyways though.

**Pull request closed without merging**
