### PR TITLE
add parameter REPEATWHENDISABLE

### PR DESCRIPTION
**Pull request by ericfont**
This parameter will repeat the midi message when enable is set to 0. The message would be identical to the initial message, (regardless of the Auto Note-Off setting).

The reason I've added this ability is so that the Mod Duo's Footswitch can send a message every time the user presses a button, instead of being limited to sending a message only every other time the user presses that button.

(The main motivation for me to do this is so I can use the Mod Duo Footswitch as a control surface for Ardour's play, stop, & record buttons)

### CODE REVIEW

**Comment by ericfont** [comment]
Oh, I am now noticing that there is a branch midi2 which has a "Momentary Button" which basically accomplishes the same goal of allowing the message to send upon disabling.  Any estimate when will that feature go live to the modduo store?

**Comment by ssj71** [comment]
yeah, I've been a bit out of the MOD scene for a while. I haven't even pulled my DUO out for a while to test that branch. That is indeed the intention with that branch. If you'll test it out for me I'll merge it and do a PR with mod to get it updated in the store. Thanks for the efforts!

**Comment by ericfont** [comment]
hmm...I can't seem to compile that mindi2 branch:

[e@Ryzen5-Radeon560 build]$ make
Scanning dependencies of target infamous-rule
[  1%] Building C object CMakeFiles/infamous-rule.dir/src/rule.c.o
[  2%] Linking C executable infamous-rule
[  2%] Built target infamous-rule
[  3%] Generating casynth_ui.h
Scanning dependencies of target casynth_ui
[  5%] Building CXX object src/casynth/CMakeFiles/casynth_ui.dir/casynth_ui_main.cxx.o
/home/e/infamousPlugins/src/casynth/casynth_ui_main.cxx:181:5: error: invalid conversion from ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} to ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} [-fpermissive]
  181 |     init_casynthUI,
      |     ^~~~~~~~~~~~~~
      |     |
      |     void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*) {aka void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)}
make[2]: *** [src/casynth/CMakeFiles/casynth_ui.dir/build.make:92: src/casynth/CMakeFiles/casynth_ui.dir/casynth_ui_main.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: src/casynth/CMakeFiles/casynth_ui.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
[e@Ryzen5-Radeon560 build]$ git status
On branch mindi2

**Comment by ericfont** [comment]
really it is just this specific commit which I believe does the feature: https://github.com/ssj71/infamousPlugins/commit/2414fb88e1ce347d5374af8239eb3045e1c1b7ec

I'm going to try to put that commit on current master and see it if works.

**Comment by ericfont** [comment]
From current master if I run:

git cherry-pick 2414fb88e1ce347d5374af8239eb3045e1c1b7ec

then the make command works.  And I'm able to test it out on my computer via Carla plugin rack.  Though I'm noticing that the momentary button feature only works for "keypressure", "cc", "prog", and "channelpressure", but doesn't work for "note on", "note off", or "pitch bend".  Is there a reason why to limit the feature to only those midi command types?  Can I add note on, note off, & pitch bend?

**Comment by ssj71** [comment]
it's been long enough I just might not remember. That sounds like a bug though. I'd be happy to look at a PR.

**Comment by ericfont** [comment]
I'll add a bit to that commit to work on all message types and test and
will submit a PR.

**Comment by ericfont** [comment]
ok, well turns out that "note on", "note off" were working just fine.  My mistake was that I was using qsynth's Message output for viewing midi messages but sent note pitches below octave 0, which qsynth ignores.  If I instead usne aseqdump to view messages, I see "note on" and "note off" work fine.

I did discover two slightly related issues with fixes:

https://github.com/ssj71/infamousPlugins/issues/44 Pitchwheel (type 14) messages incorrectly were turned into SYSEX (type 15) messages.

https://github.com/ssj71/infamousPlugins/issues/45 [Mindi] Channel pressure/aftertouch (msgtype 13) should really use DATA2 ("Value") for value, not DATA1 ("Note/CC/PG Number")

I will include fixes for those as separate commits.

**Comment by ericfont** [comment]
those last two issues are fixed in two recent commits in https://github.com/ericfont/infamousPlugins/commits/momentary-mindi2

I am still wondering what the best behavior for Note on should be for "Note on" messages when "AUTOFF" is enabled.  The current behavior seems to basically ignore AUTOFF for the momentary behavior (and only send the "Note off" when the plugin's main enable is turned off).  I haven't changed that behavior.  I am wondering what the user would expect to happen, though. 
 I'm wondering if maybe AUTOFF should result in producing a note off event after every note on event.  Of course the way to simulate this behavior is to have 0 for the non-momentary value (which I think many midi receivers would interpret like a note off).  But I think I'll remain from changing that behavior in this pull request, unless someone has a good idea the best way to interpret AUTOFF.

**Comment by ssj71** [comment]
Yes, I believe the intent of AUTOFF is indeed to prevent hanging notes. This should be consistent whether you are using the toggle enable switch or the momentary button. I agree it could be achieved by setting the velocity to 0 but that seems like a workaround. If you want to fix it that would be great, if not, I can maybe take a look after your PR is in.

**Comment by ericfont** [comment]
ok, I can fix it now.  The question is when exactly should the note off occur.  Should it occur immediately after each noteon, or should it occur immediately prior to the subsequent noteon?

**Comment by ericfont** [comment]
Should it be like:

Time 1: User presses momentary button:
Note on with momentary value
Note off
Note on with regular value
...
Time 2: User presses momentary button again
Note off
Note on with momentary value
Note off
Note on with regular value
...

or like:

Time 1: User presses momentary button:
Note on with momentary value
Note off
Note on with regular value
Note off
...
Time 2: User presses momentary button again
Note on with momentary value
Note off
Note on with regular value
Note off
...

**Comment by ericfont** [comment]
This is actually the first time I'm compiling a plugin for the mod.  I've spent quite some time trying to get the cross-compiler environment working using the docker image (https://wiki.moddevices.com/wiki/How_To_Build_and_Deploy_LV2_Plugin_to_MOD_Duo#Using_docker) and at least am able to  set my $CC and other compiler environment variables for the modduo arm target using ". ~/mod-plugin-builder/local.env modduo" and can compile simple hello world test program for the arm.  Though when compiling the mindi, at this point I'm stuck at not finding gnu/stubs-soft.h, but I'll try to figure the rest out later.

```
builder@190465a656d8:~/infamousPlugins/build/src/mindi$ make
Scanning dependencies of target mindi
[ 50%] Building C object src/mindi/CMakeFiles/mindi.dir/mindi.c.o
In file included from /home/builder/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/features.h:389:0,
                 from /home/builder/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/string.h:25,
                 from /home/builder/infamousPlugins/src/mindi/mindi.c:4:
/home/builder/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
compilation terminated.
src/mindi/CMakeFiles/mindi.dir/build.make:62: recipe for target 'src/mindi/CMakeFiles/mindi.dir/mindi.c.o' failed
make[2]: *** [src/mindi/CMakeFiles/mindi.dir/mindi.c.o] Error 1
CMakeFiles/Makefile2:704: recipe for target 'src/mindi/CMakeFiles/mindi.dir/all' failed
make[1]: *** [src/mindi/CMakeFiles/mindi.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
builder@190465a656d8:~/infamousPlugins/build/src/mindi$ echo $CC
arm-mod-linux-gnueabihf-gcc
```

**Comment by ericfont** [comment]
@ssj71, I finally was able to build the plugin for arm* and test it out on my modduo footswitch.  Here is verification video of the test build, and I assign main enable to the leftmost footswich button and the momentary to the rightmost, and when I press the momentary I am verifying in a midi event logger that I receive first an event with momentary value immediately followed by another even with the regular value:

https://www.youtube.com/watch?v=8H4UC0QpCDU

I've checked all the message types in the MESSAGE TYPE window and they work.  Channel Pressure correctly now uses VALUE for value.  And Pitchbend does result in Pitchbend (so that other issue was indeed with Carla).

One thing I'm noting with how this plugin appears in the ModDuo's GUI is that the mod only seems to show the first 16 characters of each parameters name:

image

"Note/CC/PG Number" gets shortened to "NOTE/CC/PG NUMBE"
"1st Msg Repeat Delay Time" gets shortened to "1ST MSG REPEAT D"
"Momentary Pressed Value" gets shortened to "MOMENTARY PRESSE"

So what I will rename those instead to fit within 16 characters like:

"Note/CC/PG"
"Msg Repeat Delay"
"Momentary Value"

So I will make that change too and submit a PR.  (I won't bother tryuing to figure out hte proper behavior for AUTO NOTE-OFF for now

*(To get the stubs-soft.h I installed libc6-dev-armel-cross on the xenial docker image and made a symbolic link to it from sysroot/include/gnu directory)

**Comment by ericfont** [comment]
and I guess my PR will include 3 commits.  First two are the commits from your branch:

"added momentary port to mindi"
"adding some presets and version bump for mindi"

Followed by my commit "Chan pressure should use value" which will include the naming change from data1, data2, data2b to noteccpg, value, momentaryvalue for the chan pressure to work along with changing these GUI names to fit in 16 characters.

**Comment by ericfont** [comment]
hmm...I also notice that the image for the gui image doesn't contain the repeat delay time, the auto-note off setting, the momentary button, or the momentary value in the main display.  I guess I won't bother updating the gui image to keep it simple.

**Pull request closed without merging**
